import './globals.css'
import {Roboto} from 'next/font/google'
import {SkeletonTheme} from "react-loading-skeleton";
import Navbar from "@/components/navbar";

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'], subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App', description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (<html lang="en">
    <SkeletonTheme baseColor="#202020" highlightColor="#444">
        <body className={`${roboto.className} bg-[#040713]`}>
        <Navbar/>
        <main>
            {children}
        </main>
        </body>
    </SkeletonTheme>
    </html>)
}
